### PR TITLE
Add more description about handling unknown nodes

### PR DESCRIPTION
**Pull request by Rokt33r**

### CODE REVIEW

**Review by wooorm — CHANGES_REQUESTED** [review]
How about ```to `div` nodes if they have `children` or `text` nodes if they have `value` ```

**Comment by Rokt33r** [comment]
Actually, I'm not good at English. Thanks for the suggesting. 😃😃😃

**Comment by wooorm** [comment]
This looks good! But I do think the tests will complain about line-length: could you make sure you add newlines where needed?

**Review by wooorm — APPROVED** [review]

**Comment by Rokt33r** [comment]
It's my fault because I edited directly on Github.
Hang on a little. I'm now cloning this branch to my pc.

**Comment by Rokt33r** [comment]
I've tested a new commit just now. Everything seems to be green! 💚💚

**Comment by wooorm** [comment]
Alright, great!
Thanks @Rokt33r!

**Pull request merged**
