### PR TITLE
Fix deprecation warning

### PR DESCRIPTION
**Pull request by lifeiscontent**
You forgot one

### CODE REVIEW

**Comment by lifeiscontent** [comment]
Ping @wooorm

**Comment by ChristianMurphy** [comment]
@lifeiscontent could you look into why CI is failing for this change?

**Comment by wooorm** [comment]
That’s because it wasn’t out then! https://github.com/syntax-tree/mdast-util-to-hast/commit/15d9c87b20cf617b321491940c0fff3316f5f29b

**Comment by wooorm** [comment]
I’m guessing the failure may be because of a cache in Travis? Anyway, it’s probably good to mark mdast-util-to-hast:

https://github.com/remarkjs/remark-html/blob/8a4d280a3e4df4a6d28be4240f83d7c7a6709695/package.json#L37

as:

```
    "mdast-util-to-hast": "^8.2.0",
```

**Review by mabhub — APPROVED** [review]

**Comment by lifeiscontent** [comment]
@wooorm do I need to do something here?

**Comment by wooorm** [comment]
could you change the version number? https://github.com/remarkjs/remark-html/pull/29#issuecomment-612343715

**Comment by josemarluedke** [comment]
Any chance we can move this forward?

**Comment by wooorm** [comment]
Released!

**Pull request closed without merging**
